# Generated by Django 5.1.1 on 2024-10-06 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_auction_listing_user_watchlist_bid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction_listing",
            name="current_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to="auctions.bid",
            ),
        ),
    ]
