# Generated by Django 5.1.1 on 2024-10-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_auction_listing_current_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="selling",
            field=models.ManyToManyField(
                blank=True, related_name="sold_by", to="auctions.auction_listing"
            ),
        ),
    ]
