# Generated by Django 5.1.1 on 2024-10-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_user_selling"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="selling",),
    ]
