# Generated by Django 5.1.1 on 2024-10-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_user_selling"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction_listing",
            old_name="closing_date",
            new_name="closing_time",
        ),
    ]
