# Generated by Django 5.1.1 on 2024-10-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_auction_listing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="purchases",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_by",
                to="auctions.auction_listing",
            ),
        ),
    ]
