# Generated by Django 5.1.1 on 2024-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_user_purchases"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="purchases",),
        migrations.AddField(
            model_name="user",
            name="purchases",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="purchased_by",
                to="auctions.auction_listing",
            ),
        ),
    ]
