# Generated by Django 5.1.1 on 2024-10-13 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_alter_user_purchases"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction_listing",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="auctions.comment",
            ),
        ),
    ]
